package com.winga.domain.enums;

public enum NotificationType {
    JOB_POSTED,
    JOB_APPROVED,
    JOB_REJECTED,
    PROPOSAL_RECEIVED,
    PROPOSAL_SHORTLISTED,
    PROPOSAL_REJECTED,
    HIRED,
    WORK_SUBMITTED,
    WORK_APPROVED,
    PAYMENT_RELEASED,
    DISPUTE_OPENED,
    DISPUTE_RESOLVED,
    MILESTONE_FUNDED,
    MILESTONE_COMPLETED,
    MESSAGE_RECEIVED,
    SYSTEM
}
